# Site settings
title: Madhym Tech
description: >-
  He's writing in Delhi about web technology that he learned, meet him <a href="https://www.linkedin.com/in/ayush-garg-5bb04114b/" target="_blank" rel="noopener">@Linkedin</a>.
lang: en-US
timezone: Asia/Kolkata
image: assets/img/ogp.png 
repo: https://github.com/ayush-garg341/blogs
mode: dark # default theme "dark" | "light"
twitter_username: ayush_garg341

# Profile settings
author:
  name: Ayush Garg
  bio: >-
     Full Stack Software engineer @Tripock Labs with over all experience of 2+ year in full stack development. Here is more to my profession <a href="https://www.linkedin.com/in/ayush-garg-5bb04114b/" target="_blank" rel="noopener">@Linkedin</a>.
  username: gargayush341
  email: gargayush341@gmail.com
  avatar: /assets/img/avatar.jpg
  github_username: ayush-garg341

# Url settings
url: "https://madhym.tech"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
